# Numpy, Pandas, Matplotlib, Data Cleaning and Pandas SQL
# Assignment 1

In [1]:
import numpy as np
import os
import pandas as pd

## Use Cases on Numpy and Pandas

1.) Write a Python program which accepts a list named : randomList = ['a', 0, 2]. Use exception handling using try-catch which gives the output as:
Output:
    1) If the List element is a alphabet or string, the output will be
    The entry is a
    Oops! <class 'ValueError'> occured.
    Next entry.
    2) If the List element is “0”,the output will be
    The entry is 0
    Oops! <class 'ZeroDivisionError'> occured.
    Next entry.
    3) If the List element is and integer except 0,then output will be:
    The entry is 2
    The reciprocal of 2 is 0.5 // reciprocal of an integer

In [23]:
try:
    randomList = ['a', 0, 2]
    for item in randomList:
        if item == 'a':
            print ('The entry is %s' %item)
            print ("Oops! <class 'ValueError'> occured")
            print ('Next entry')
        elif item == 0:
            print ('The entry is 0')
            print ("Oops! <class 'ZeroDivisionError'> occured")
            print ('Next entry')
        elif item != 0:
            print ('The entry is %d' %item)
            print ('The reciprocal of %s is %f' %(item, 1/item))
except Exception as e:
    print ("Oops! <class '%s'> occured" %e)

The entry is a
Oops! <class 'ValueError'> occured
Next entry
The entry is 0
Oops! <class 'ZeroDivisionError'> occured
Next entry
The entry is 2
The reciprocal of 2 is 0.500000

2) Array out of Bound Exception
Write a Python program to give exception “Array Out of Bound” 
if the user wants to access the elements beyond the list size (use try and except)

In [2]:
l1 = [1,2,3,4,5,6]
try:
    print (l1[6])
except Exception as e:
    print ("Array Out of Bound")

Array Out of Bound

3) Write a python module script that contains fib2() method to calculate the Fibonacci series till 1000 and save it as fibo.py.

In [3]:
def fib2(max_limit):
    fib_list = [1,1]
    for i in range(2, max_limit):
        next_item = fib_list[i-1] + fib_list[i-2]
        if next_item < max_limit:
            fib_list.append(next_item)
        else:
            break
    return fib_list

In [4]:
fib2(1000)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]

4) Write a python module script that contains ispalindrome() method to calculate the input string as palindrome string or not and save it as palindrome.py.

In [5]:
def ispalindrome(check_item):
    check_item = str(check_item)
    rev_item = check_item[::-1]
    if rev_item == check_item:
        return True
    else:
        return False

In [6]:
ispalindrome('aba')

True

In [7]:
ispalindrome('abc')

False

 5) Write a program in Python with one class called Cipher. Within the constructor of this class, ask user for a string and store it. Use a static variable, key to store a randomly generated integer between 1 and 50 inclusive. Implement two methods, encrypt and decrypt within this class. Encrypt generates and prints a cipher text using the user-entered string and the key and ecrypt generates decrypted string from ciphertext. The cipher only encrypts alpha and numeric (A-Z, a-z, 0-9). All Symbols, such as - , ; %, remain unencrypted. The cipher text can have special characters. Use generator expression to filter out alpha and numeric characters of the input string and to generate cipher text. Create an instance of this class, encrypt and decrypt back the user entered string.

In [3]:
class Cipher():
    key = np.random.randint(1,50)
    key_file = open("C:\\Users\\VAIBHAV\\Acadgild\\key", 'w')
    key_file.write(str(key))
    key_file.close()

    def __init__(self):
        self.in_str = input("Enter string to encrypt/decrypt: ")
    
    def encrypt(self):
        encrypt_chars = []
        key = Cipher.key
        for i in range(len(self.in_str)):
            #key_c = key[i % len(key)]
            encrypt_c = chr(ord(self.in_str[i]) + key % 256)
            encrypt_chars.append(encrypt_c)
        encrypt_string = "".join(encrypt_chars)
        print ("encoded_string: ", encrypt_string)
        return encrypt_string
    
    def decrypt(self, encr_str=""):
        decrypted_chars = []
        key = Cipher.key
        for i in range(len(encr_str)):
            #key_c = key[i % len(key)]
            decrypted_c = chr(ord(encr_str[i]) - key % 256)
            decrypted_chars.append(decrypted_c)
        decrypted_string = "".join(decrypted_chars)
        print ("decrypted_string: ", decrypted_string)
        return decrypted_string

In [4]:
ci = Cipher()

Enter string to encrypt/decrypt: VaibhaV221

In [6]:
encr_str = ci.encrypt()

encoded_string:  altmsla==<

In [7]:
ci.decrypt(encr_str)

decrypted_string:  VaibhaV221

'VaibhaV221'

6) Get Data from the following link:
http://files.grouplens.org/datasets/movielens/ml-20m.zip

We will be using the following files for this exercise:

ratings.csv : userId,movieId,rating, timestamp

tags.csv : userId,movieId, tag, timestamp

movies.csv : movieId, title, genres

I. Read the dataset using pandas.

II. Extract the first row from tags and print its type.

III. Extract row 0, 11, 2000 from tags DataFrame.

IV. Print index, columns of the DataFrame.

V. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().

VI. Filter out ratings with rating > 5

VII. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.

VIII. Filter out movies from the movies DataFrame that are of type 'Animation'.

IX. Find the average rating of movies.

X. Perform an inner join of movies and tags based on movieId.

XI. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.

XII. Split 'genres' into multiple columns.

XIII. Extract year from title e.g. (1995).

XIV. Select rows based on timestamps later than 2015-02-01.

XV. Sort the tags DataFrame based on timestamp.

In [4]:
os.chdir('C:\\Users\\VAIBHAV\\Acadgild\\Assignment 6 -11\\ml-20m')

In [11]:
os.listdir()

['genome-scores.csv',
 'genome-tags.csv',
 'links.csv',
 'movies.csv',
 'ratings.csv',
 'README.txt',
 'tags.csv']

I. Read the dataset using pandas.

In [5]:
ratings = pd.read_csv('ratings.csv')

In [13]:
ratings.head()

   userId  movieId  rating   timestamp
0       1        2     3.5  1112486027
1       1       29     3.5  1112484676
2       1       32     3.5  1112484819
3       1       47     3.5  1112484727
4       1       50     3.5  1112484580

In [6]:
tags = pd.read_csv('tags.csv')

In [15]:
tags.head()

   userId  movieId            tag   timestamp
0      18     4141    Mark Waters  1240597180
1      65      208      dark hero  1368150078
2      65      353      dark hero  1368150079
3      65      521  noir thriller  1368149983
4      65      592      dark hero  1368150078

In [7]:
movies = pd.read_csv('movies.csv')

In [17]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

II. Extract the first row from tags and print its type.

In [19]:
tags.loc[1]

userId               65
movieId             208
tag           dark hero
timestamp    1368150078
Name: 1, dtype: object

In [20]:
type(tags.loc[1])

pandas.core.series.Series

III. Extract row 0, 11, 2000 from tags DataFrame.

In [22]:
tags.loc[[0,11,2000]]

      userId  movieId                tag   timestamp
0         18     4141        Mark Waters  1240597180
11        65     1783      noir thriller  1368149983
2000     910    68554  conspiracy theory  1368043943

IV. Print index, columns of the DataFrame.

In [23]:
tags.index

RangeIndex(start=0, stop=465564, step=1)

In [24]:
tags.columns

Index(['userId', 'movieId', 'tag', 'timestamp'], dtype='object')

V. Calculate descriptive statistics for the 'ratings' column of the ratings DataFrame. Verify using describe().

In [25]:
ratings['rating'].count()

20000263

In [26]:
ratings['rating'].mean()

3.5255285642993797

In [27]:
ratings['rating'].min()

0.5

In [28]:
ratings['rating'].max()

5.0

In [30]:
ratings['rating'].std()

1.051988919275684

In [29]:
ratings.describe()

             userId       movieId        rating     timestamp
count  2.000026e+07  2.000026e+07  2.000026e+07  2.000026e+07
mean   6.904587e+04  9.041567e+03  3.525529e+00  1.100918e+09
std    4.003863e+04  1.978948e+04  1.051989e+00  1.621694e+08
min    1.000000e+00  1.000000e+00  5.000000e-01  7.896520e+08
25%    3.439500e+04  9.020000e+02  3.000000e+00  9.667977e+08
50%    6.914100e+04  2.167000e+03  3.500000e+00  1.103556e+09
75%    1.036370e+05  4.770000e+03  4.000000e+00  1.225642e+09
max    1.384930e+05  1.312620e+05  5.000000e+00  1.427784e+09

VI. Filter out ratings with rating > 5

In [31]:
#since max rating is 5, so no rows value
ratings[ratings['rating']>5]

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

VII. Find how many null values, missing values are present. Deal with them. Print out how many rows have been modified.

In [36]:
tags.isnull().sum()

userId        0
movieId       0
tag          16
timestamp     0
dtype: int64

In [38]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [39]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [40]:
tags.fillna(0)

,userId,movieId,tag,timestamp
0,18,4141,Mark Waters,1240597180
1,65,208,dark hero,1368150078
2,65,353,dark hero,1368150079
3,65,521,noir thriller,1368149983
4,65,592,dark hero,1368150078
5,65,668,bollywood,1368149876
6,65,898,screwball comedy,1368150160
7,65,1248,noir thriller,1368149983
8,65,1391,mars,1368150055
9,65,1617,neo-noir,1368150217
10,65,1694,jesus,1368149925
11,65,1783,noir thriller,1368149983
12,65,2022,jesus,1368149925
13,65,2193,dragon,1368151314
14,65,2353,conspiracy theory,1368151266
15,65,2662,mars,1368150055
16,65,2726,noir thriller,1368149983
17,65,2840,jesus,1368149925
18,65,3052,jesus,1368149926
19,65,5135,bollywood,1368149876
20,65,6539,treasure,1368149949
21,65,6874,dark hero,1368150079
22,65,7013,noir thriller,1368149983
23,65,7318,jesus,1368149925
24,65,8529,stranded,1368150012
25,65,8622,conspiracy theory,1368151266
26,65,27803,Oscar (Best Foreign Language Film),1305008715
27,65,27866,New Zealand,1304957153
28,65,48082,surreal,1304958354
29,65,48082,unusual,1304958359
...,...,...,...,...
465534,138436,81932,big hair,1298754654
465535,138436,81932,Mark Wahlberg,1298754636
465536,138436,81932,pigs,1298754658
465537,138436,81932,prostitution,1298754620
465538,138437,77154,"This movie should have been called ""How Cocain...",1357384633
465539,138446,317,Christmas,1358983914
465540,138446,317,funny,1358983914
465541,138446,317,Judge Reinhold,1358983914
465542,138446,317,Tim Allen,1358983914
465543,138446,317,whiny kid,1358983946
465544,138446,837,family friendly,1358983693
465545,138446,918,halloween scene,1358984062
465546,138446,918,quirky,1358984051
465547,138446,2396,topless scene,1358973995
465548,138446,3086,Christmas,1358983979
465549,138446,3086,classic,1358983979
465550,138446,3086,funny,1358983979
465551,138446,3086,scary,1358984001
465552,138446,3489,Peter Pan,1358983822
465553,138446,3489,soundtrack,1358983822
465554,138446,3489,visually appealing,1358983822
465555,138446,7045,family friendly,1358983660
465556,138446,7045,Scary Movies To See on Halloween,1358983660
465557,138446,7164,Peter Pan,1358983855
465558,138446,7164,visually appealing,1358983855
465559,138446,55999,dragged,1358983772
465560,138446,55999,Jason Bateman,1358983778
465561,138446,55999,quirky,1358983778
465562,138446,55999,sad,1358983772
465563,138472,923,rise to power,1194037967

VIII. Filter out movies from the movies DataFrame that are of type 'Animation'.

In [35]:
movies[movies['genres'].str.contains('Animation')]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
12,13,Balto (1995),Adventure|Animation|Children
47,48,Pocahontas (1995),Animation|Children|Drama|Musical|Romance
236,239,"Goofy Movie, A (1995)",Animation|Children|Comedy|Romance
241,244,Gumby: The Movie (1995),Animation|Children
310,313,"Swan Princess, The (1994)",Animation|Children
360,364,"Lion King, The (1994)",Adventure|Animation|Children|Drama|Musical|IMAX
388,392,"Secret Adventures of Tom Thumb, The (1993)",Adventure|Animation
547,551,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
553,558,"Pagemaster, The (1994)",Action|Adventure|Animation|Children|Fantasy
582,588,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
588,594,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
589,595,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX
590,596,Pinocchio (1940),Animation|Children|Fantasy|Musical
604,610,Heavy Metal (1981),Action|Adventure|Animation|Horror|Sci-Fi
610,616,"Aristocats, The (1970)",Animation|Children
624,631,All Dogs Go to Heaven 2 (1996),Adventure|Animation|Children|Fantasy|Musical|R...
653,661,James and the Giant Peach (1996),Adventure|Animation|Children|Fantasy|Musical
664,673,Space Jam (1996),Adventure|Animation|Children|Comedy|Fantasy|Sc...
697,709,Oliver & Company (1988),Adventure|Animation|Children|Comedy|Musical
708,720,Wallace & Gromit: The Best of Aardman Animatio...,Adventure|Animation|Comedy
728,741,Ghost in the Shell (Kôkaku kidôtai) (1995),Animation|Sci-Fi
732,745,Wallace & Gromit: A Close Shave (1995),Animation|Children|Comedy
770,783,"Hunchback of Notre Dame, The (1996)",Animation|Children|Drama|Musical|Romance
871,888,Land Before Time III: The Time of the Great Gi...,Adventure|Animation|Children|Musical
1003,1022,Cinderella (1950),Animation|Children|Fantasy|Musical|Romance
1004,1023,Winnie the Pooh and the Blustery Day (1968),Animation|Children|Musical
1005,1024,"Three Caballeros, The (1945)",Animation|Children|Musical
1006,1025,"Sword in the Stone, The (1963)",Animation|Children|Fantasy|Musical
1010,1029,Dumbo (1941),Animation|Children|Drama|Musical
...,...,...,...
27007,129830,Animals United (2011),Animation|Children|Comedy
27008,129834,Tom and Jerry: The Lost Dragon (2014),Animation|Children|Comedy
27018,129859,Mardock Scramble: The Second Combustion (2011),Animation|Sci-Fi
27054,130034,Stand by Me Doraemon (2014),Animation|Children|Drama|Fantasy
27070,130075,Frozen Fever (2015),Adventure|Animation
27103,130394,The Mascot (1934),Animation
27107,130402,Cardcaptor Sakura: The Sealed Card (2000),Adventure|Animation|Comedy|Fantasy|Romance
27129,130506,Berserk: The Golden Age Arc 2 - The Battle for...,Action|Animation|Fantasy
27130,130508,Berserk: The Golden Age Arc - The Egg of the K...,Action|Adventure|Animation|Fantasy|Horror
27131,130510,Berserk: The Golden Age Arc 3 - Descent (2013),Action|Animation|Fantasy
27135,130518,The Amazing Screw-On Head (2006),Action|Adventure|Animation|Comedy|Sci-Fi
27136,130520,Home (2015),Animation|Children|Comedy|Fantasy|Sci-Fi
27137,130522,The Brave Little Toaster Goes to Mars (1998),Animation|Children
27155,130644,The Garden of Sinners - Chapter 5: Paradox Par...,Animation
27205,131058,Santa's Apprentice (2010),Animation|Children
27208,131066,Ronal the Barbarian (2011),Adventure|Animation|Fantasy
27215,131080,Cinderella III: A Twist in Time (2007),Animation|Children|Fantasy|Romance
27218,131086,The Little Polar Bear: Lars and the Little Tig...,Animation|Children
27221,131092,"Mickey, Donald, Goofy: The Three Musketeers (2...",Adventure|Animation|Children|Comedy
27222,131094,Rudolph the Red-Nosed Reindeer: The Movie (1998),Animation|Children
27224,131098,Saving Santa (2013),Animation|Children|Comedy
27226,131102,Lucky Luke: The Ballad of the Daltons (1978),Animation|Children|Comedy|Western
27228,131106,Casper's Haunted Christmas (2000),Animation|Children
27235,131120,Superstar Goofy (1991),Animation|Children|Comedy
27240,131130,Tom and Jerry: A Nutcracker Tale (2007),Animation|Comedy
27241,131132,Kleines Arschloch - Der Film (1997),Animation|Comedy
27247,131144,Werner - Das muss kesseln!!! (1996),Animation|Comedy
27248,131146,Werner - Volles Rooäää (1999),Animation|Comedy
27269,131243,Werner - Gekotzt wird später (2003),Animation|Comedy
27270,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy

IX. Find the average rating of movies.

In [34]:
ratings.groupby('movieId')['rating'].mean()

movieId
1         3.921240
2         3.211977
3         3.151040
4         2.861393
5         3.064592
6         3.834930
7         3.366484
8         3.142049
9         3.004924
10        3.430029
11        3.667713
12        2.619766
13        3.272416
14        3.432082
15        2.721993
16        3.787455
17        3.968573
18        3.373631
19        2.607412
20        2.880754
21        3.581689
22        3.319400
23        3.148235
24        3.199849
25        3.689510
26        3.628857
27        3.413520
28        4.057546
29        3.952230
30        3.633880
            ...
131146    4.000000
131148    4.000000
131150    4.000000
131152    0.500000
131154    3.500000
131156    4.000000
131158    4.000000
131160    4.000000
131162    2.000000
131164    4.000000
131166    4.000000
131168    3.500000
131170    3.500000
131172    1.000000
131174    3.500000
131176    4.500000
131180    2.500000
131231    3.500000
131237    3.000000
131239    4.000000
131241    4.000000
131243    4.000000
131248    4.000000
131250    4.000000
131252    4.000000
131254    4.000000
131256    4.000000
131258    2.500000
131260    3.000000
131262    4.000000
Name: rating, Length: 26744, dtype: float64

X. Perform an inner join of movies and tags based on movieId.

In [55]:
movies.join(tags, on=['movieId'], how='inner',lsuffix='_movies_id',rsuffix='_tags_id')

,movieId,movieId_movies_id,title,genres,year,userId,movieId_tags_id,tag,timestamp
0,1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Toy Story , 1995)]",65,208,dark hero,1368150078
1,2,2,Jumanji (1995),Adventure|Children|Fantasy,"[Jumanji , 1995)]",65,353,dark hero,1368150079
2,3,3,Grumpier Old Men (1995),Comedy|Romance,"[Grumpier Old Men , 1995)]",65,521,noir thriller,1368149983
3,4,4,Waiting to Exhale (1995),Comedy|Drama|Romance,"[Waiting to Exhale , 1995)]",65,592,dark hero,1368150078
4,5,5,Father of the Bride Part II (1995),Comedy,"[Father of the Bride Part II , 1995)]",65,668,bollywood,1368149876
5,6,6,Heat (1995),Action|Crime|Thriller,"[Heat , 1995)]",65,898,screwball comedy,1368150160
6,7,7,Sabrina (1995),Comedy|Romance,"[Sabrina , 1995)]",65,1248,noir thriller,1368149983
7,8,8,Tom and Huck (1995),Adventure|Children,"[Tom and Huck , 1995)]",65,1391,mars,1368150055
8,9,9,Sudden Death (1995),Action,"[Sudden Death , 1995)]",65,1617,neo-noir,1368150217
9,10,10,GoldenEye (1995),Action|Adventure|Thriller,"[GoldenEye , 1995)]",65,1694,jesus,1368149925
10,11,11,"American President, The (1995)",Comedy|Drama|Romance,"[American President, The , 1995)]",65,1783,noir thriller,1368149983
11,12,12,Dracula: Dead and Loving It (1995),Comedy|Horror,"[Dracula: Dead and Loving It , 1995)]",65,2022,jesus,1368149925
12,13,13,Balto (1995),Adventure|Animation|Children,"[Balto , 1995)]",65,2193,dragon,1368151314
13,14,14,Nixon (1995),Drama,"[Nixon , 1995)]",65,2353,conspiracy theory,1368151266
14,15,15,Cutthroat Island (1995),Action|Adventure|Romance,"[Cutthroat Island , 1995)]",65,2662,mars,1368150055
15,16,16,Casino (1995),Crime|Drama,"[Casino , 1995)]",65,2726,noir thriller,1368149983
16,17,17,Sense and Sensibility (1995),Drama|Romance,"[Sense and Sensibility , 1995)]",65,2840,jesus,1368149925
17,18,18,Four Rooms (1995),Comedy,"[Four Rooms , 1995)]",65,3052,jesus,1368149926
18,19,19,Ace Ventura: When Nature Calls (1995),Comedy,"[Ace Ventura: When Nature Calls , 1995)]",65,5135,bollywood,1368149876
19,20,20,Money Train (1995),Action|Comedy|Crime|Drama|Thriller,"[Money Train , 1995)]",65,6539,treasure,1368149949
20,21,21,Get Shorty (1995),Comedy|Crime|Thriller,"[Get Shorty , 1995)]",65,6874,dark hero,1368150079
21,22,22,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,"[Copycat , 1995)]",65,7013,noir thriller,1368149983
22,23,23,Assassins (1995),Action|Crime|Thriller,"[Assassins , 1995)]",65,7318,jesus,1368149925
23,24,24,Powder (1995),Drama|Sci-Fi,"[Powder , 1995)]",65,8529,stranded,1368150012
24,25,25,Leaving Las Vegas (1995),Drama|Romance,"[Leaving Las Vegas , 1995)]",65,8622,conspiracy theory,1368151266
25,26,26,Othello (1995),Drama,"[Othello , 1995)]",65,27803,Oscar (Best Foreign Language Film),1305008715
26,27,27,Now and Then (1995),Children|Drama,"[Now and Then , 1995)]",65,27866,New Zealand,1304957153
27,28,28,Persuasion (1995),Drama|Romance,"[Persuasion , 1995)]",65,48082,surreal,1304958354
28,29,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,"[City of Lost Children, The , Cité des enfants...",65,48082,unusual,1304958359
29,30,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Crime|Drama,"[Shanghai Triad , Yao a yao yao dao waipo qiao...",65,51884,bollywood,1368149876
...,...,...,...,...,...,...,...,...,...
27248,131146,131146,Werner - Volles Rooäää (1999),Animation|Comedy,"[Werner - Volles Rooäää , 1999)]",34494,53956,Nudity (Rear),1326402278
27249,131148,131148,What A Man (2011),Comedy|Romance,"[What A Man , 2011)]",34494,53956,wheelchair,1326402295
27250,131150,131150,7 Dwarves: The Forest Is Not Enough (2006),Comedy,"[7 Dwarves: The Forest Is Not Enough , 2006)]",34494,56719,prodigy,1326535978
27251,131152,131152,The Fat Spy (1966),Comedy,"[The Fat Spy , 1966)]",34494,58998,break-up,1327260156
27252,131154,131154,"Die Bademeister – Weiber, saufen, Leben retten...",Comedy,"[Die Bademeister – Weiber, saufen, Leben rette...",34494,58998,Hawaii,1327260176
27253,131156,131156,Ants in the Pants 2 (2002),Comedy,"[Ants in the Pants 2 , 2002)]",34494,58998,jealousy,1327260186
27254,131158,131158,"Manta, Manta (1991)",Comedy,"[Manta, Manta , 1991)]",34494,58998,Nudity (Full Frontal - Notable),1327260193
27255,131160,131160,Oscar and the Lady in Pink (2009),Drama,"[Oscar and the Lady in Pink , 2009)]",34494,58998,puppets,1327260247
27256,131162,131162,Por un puñado de besos (2014),Drama|Romance,"[Por un puñado de besos , 2014)]",34494,58998,surfing,1327260243
27257,131164,131164,Vietnam in HD (2011),War,"[Vietnam in HD , 2011)]",34494,60069,Comedy,1322934956
27258,131166,131166,WWII IN HD (2009),(no genres listed),"[WWII IN HD , 2009)]",34494,60069,robots,1322934947
27259,131168,131168,Phoenix (2014),Drama,"[Phoenix , 2014)]",34494,60408,hilarious,1322934874
27260,131170,131170,Parallels (2015),Sci-Fi,"[Parallels , 2015)]",34494,61323,Brad Pitt,1326646054
27261,131172,131172,Closed Curtain (2013),(no genres listed),"[Closed Curtain , 2013)]",34494,61323,cosmetic surgery,1326646075
27262,131174,131174,Gentlemen (2014),Drama|Romance|Thriller,"[Gentlemen , 2014)]",34494,61323,George Clooney,1326646092
27263,131176,131176,A Second Chance (2014),Drama,"[A Second Chance , 2014)]",34494,61323,John Malkovich,1326646067
27264,131180,131180,Dead Rising: Watchtower (2015),Action|Horror|Thriller,"[Dead Rising: Watchtower , 2015)]",34494,64614,Clint Eastwood,1323542837
27265,131231,131231,Standby (2014),Comedy|Romance,"[Standby , 2014)]",34494,73587,sexuality,1323469711
27266,131237,131237,What Men Talk About (2010),Comedy,"[What Men Talk About , 2010)]",34494,76093,dragons,1325326591
27267,131239,131239,Three Quarter Moon (2011),Comedy|Drama,"[Three Quarter Moon , 2011)]",34494,76093,friendship,1325326636
27268,131241,131241,Ants in the Pants (2000),Comedy|Romance,"[Ants in the Pants , 2000)]",34494,77191,dark comedy,1326402404
27269,131243,131243,Werner - Gekotzt wird später (2003),Animation|Comedy,"[Werner - Gekotzt wird später , 2003)]",34494,77191,male nudity,1326402427
27270,131248,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy,"[Brother Bear 2 , 2006)]",34494,78321,sexuality,1326228885
27271,131250,131250,No More School (2000),Comedy,"[No More School , 2000)]",34494,79132,alternate reality,1325326442
27272,131252,131252,Forklift Driver Klaus: The First Day on the Jo...,Comedy|Horror,[Forklift Driver Klaus: The First Day on the J...,34494,79132,dreamlike,1325326562
27273,131254,131254,Kein Bund für's Leben (2007),Comedy,"[Kein Bund für's Leben , 2007)]",34494,79132,fantasy,1325326456
27274,131256,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,"[Feuer, Eis & Dosenbier , 2002)]",34494,79132,Leonardo DiCaprio,1325326461
27275,131258,131258,The Pirates (2014),Adventure,"[The Pirates , 2014)]",34494,79132,sci-fi,1325326474
27276,131260,131260,Rentun Ruusu (2001),(no genres listed),"[Rentun Ruusu , 2001)]",34494,79132,thought-provoking,1325326483
27277,131262,131262,Innocence (2014),Adventure|Fantasy|Horror,"[Innocence , 2014)]",34494,79590,AGE DISPARITY ROMANCE,1326319089

XI. Print out the 5 movies that belong to the Comedy genre and have rating greater than 4.

In [63]:
movie_rating = pd.merge(movies,ratings)

In [78]:
movie_rating[(movie_rating['genres'].str.contains('Comedy')) & (movie_rating['rating']>4)].head()

,movieId,title,genres,year,userId,rating,timestamp
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Toy Story , 1995)]",6,5.0,858275452
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Toy Story , 1995)]",11,4.5,1230858821
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Toy Story , 1995)]",14,4.5,1225311239
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Toy Story , 1995)]",19,5.0,855176628
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"[Toy Story , 1995)]",34,5.0,846509445

XII. Split 'genres' into multiple columns.

In [14]:
print(movies.genres.apply(lambda x: pd.Series(str(x).split("|"))))

                        0          1         2        3         4    5    6  \
0               Adventure  Animation  Children   Comedy   Fantasy  NaN  NaN
1               Adventure   Children   Fantasy      NaN       NaN  NaN  NaN
2                  Comedy    Romance       NaN      NaN       NaN  NaN  NaN
3                  Comedy      Drama   Romance      NaN       NaN  NaN  NaN
4                  Comedy        NaN       NaN      NaN       NaN  NaN  NaN
5                  Action      Crime  Thriller      NaN       NaN  NaN  NaN
6                  Comedy    Romance       NaN      NaN       NaN  NaN  NaN
7               Adventure   Children       NaN      NaN       NaN  NaN  NaN
8                  Action        NaN       NaN      NaN       NaN  NaN  NaN
9                  Action  Adventure  Thriller      NaN       NaN  NaN  NaN
10                 Comedy      Drama   Romance      NaN       NaN  NaN  NaN
11                 Comedy     Horror       NaN      NaN       NaN  NaN  NaN
12              Adventure  Animation  Children      NaN       NaN  NaN  NaN
13                  Drama        NaN       NaN      NaN       NaN  NaN  NaN
14                 Action  Adventure   Romance      NaN       NaN  NaN  NaN
15                  Crime      Drama       NaN      NaN       NaN  NaN  NaN
16                  Drama    Romance       NaN      NaN       NaN  NaN  NaN
17                 Comedy        NaN       NaN      NaN       NaN  NaN  NaN
18                 Comedy        NaN       NaN      NaN       NaN  NaN  NaN
19                 Action     Comedy     Crime    Drama  Thriller  NaN  NaN
20                 Comedy      Crime  Thriller      NaN       NaN  NaN  NaN
21                  Crime      Drama    Horror  Mystery  Thriller  NaN  NaN
22                 Action      Crime  Thriller      NaN       NaN  NaN  NaN
23                  Drama     Sci-Fi       NaN      NaN       NaN  NaN  NaN
24                  Drama    Romance       NaN      NaN       NaN  NaN  NaN
25                  Drama        NaN       NaN      NaN       NaN  NaN  NaN
26               Children      Drama       NaN      NaN       NaN  NaN  NaN
27                  Drama    Romance       NaN      NaN       NaN  NaN  NaN
28              Adventure      Drama   Fantasy  Mystery    Sci-Fi  NaN  NaN
29                  Crime      Drama       NaN      NaN       NaN  NaN  NaN
...                   ...        ...       ...      ...       ...  ...  ...
27248           Animation     Comedy       NaN      NaN       NaN  NaN  NaN
27249              Comedy    Romance       NaN      NaN       NaN  NaN  NaN
27250              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27251              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27252              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27253              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27254              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27255               Drama        NaN       NaN      NaN       NaN  NaN  NaN
27256               Drama    Romance       NaN      NaN       NaN  NaN  NaN
27257                 War        NaN       NaN      NaN       NaN  NaN  NaN
27258  (no genres listed)        NaN       NaN      NaN       NaN  NaN  NaN
27259               Drama        NaN       NaN      NaN       NaN  NaN  NaN
27260              Sci-Fi        NaN       NaN      NaN       NaN  NaN  NaN
27261  (no genres listed)        NaN       NaN      NaN       NaN  NaN  NaN
27262               Drama    Romance  Thriller      NaN       NaN  NaN  NaN
27263               Drama        NaN       NaN      NaN       NaN  NaN  NaN
27264              Action     Horror  Thriller      NaN       NaN  NaN  NaN
27265              Comedy    Romance       NaN      NaN       NaN  NaN  NaN
27266              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27267              Comedy      Drama       NaN      NaN       NaN  NaN  NaN
27268              Comedy    Romance       NaN      NaN       NaN  NaN  NaN
27269           Animation     Comedy       NaN      NaN       NaN  NaN  NaN
27270           Adventure  Animation  Children   Comedy   Fantasy  NaN  NaN
27271              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27272              Comedy     Horror       NaN      NaN       NaN  NaN  NaN
27273              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27274              Comedy        NaN       NaN      NaN       NaN  NaN  NaN
27275           Adventure        NaN       NaN      NaN       NaN  NaN  NaN
27276  (no genres listed)        NaN       NaN      NaN       NaN  NaN  NaN
27277           Adventure    Fantasy    Horror      NaN       NaN  NaN  NaN

         7    8    9
0      NaN  NaN  NaN
1      NaN  NaN  NaN
2      NaN  NaN  NaN
3      NaN  NaN  NaN
4      NaN  NaN  NaN
5      NaN  NaN  NaN
6      NaN  NaN  NaN
7      NaN  NaN  NaN
8      NaN  NaN  NaN
9      NaN  NaN  NaN
10     NaN  NaN  NaN
11     NaN  NaN  NaN
12     NaN  NaN  NaN
13     NaN  NaN  NaN
14     NaN  NaN  NaN
15     NaN  NaN  NaN
16     NaN  NaN  NaN
17     NaN  NaN  NaN
18     NaN  NaN  NaN
19     NaN  NaN  NaN
20     NaN  NaN  NaN
21     NaN  NaN  NaN
22     NaN  NaN  NaN
23     NaN  NaN  NaN
24     NaN  NaN  NaN
25     NaN  NaN  NaN
26     NaN  NaN  NaN
27     NaN  NaN  NaN
28     NaN  NaN  NaN
29     NaN  NaN  NaN
...    ...  ...  ...
27248  NaN  NaN  NaN
27249  NaN  NaN  NaN
27250  NaN  NaN  NaN
27251  NaN  NaN  NaN
27252  NaN  NaN  NaN
27253  NaN  NaN  NaN
27254  NaN  NaN  NaN
27255  NaN  NaN  NaN
27256  NaN  NaN  NaN
27257  NaN  NaN  NaN
27258  NaN  NaN  NaN
27259  NaN  NaN  NaN
27260  NaN  NaN  NaN
27261  NaN  NaN  NaN
27262  NaN  NaN  NaN
27263  NaN  NaN  NaN
27264  NaN  NaN  NaN
27265  NaN  NaN  NaN
27266  NaN  NaN  NaN
27267  NaN  NaN  NaN
27268  NaN  NaN  NaN
27269  NaN  NaN  NaN
27270  NaN  NaN  NaN
27271  NaN  NaN  NaN
27272  NaN  NaN  NaN
27273  NaN  NaN  NaN
27274  NaN  NaN  NaN
27275  NaN  NaN  NaN
27276  NaN  NaN  NaN
27277  NaN  NaN  NaN

[27278 rows x 10 columns]

XIII. Extract year from title e.g. (1995).

In [34]:
print(movies.title.str.extract(r'(\(\d\d\d\d\))'))

            0
0      (1995)
1      (1995)
2      (1995)
3      (1995)
4      (1995)
5      (1995)
6      (1995)
7      (1995)
8      (1995)
9      (1995)
10     (1995)
11     (1995)
12     (1995)
13     (1995)
14     (1995)
15     (1995)
16     (1995)
17     (1995)
18     (1995)
19     (1995)
20     (1995)
21     (1995)
22     (1995)
23     (1995)
24     (1995)
25     (1995)
26     (1995)
27     (1995)
28     (1995)
29     (1995)
...       ...
27248  (1999)
27249  (2011)
27250  (2006)
27251  (1966)
27252  (1999)
27253  (2002)
27254  (1991)
27255  (2009)
27256  (2014)
27257  (2011)
27258  (2009)
27259  (2014)
27260  (2015)
27261  (2013)
27262  (2014)
27263  (2014)
27264  (2015)
27265  (2014)
27266  (2010)
27267  (2011)
27268  (2000)
27269  (2003)
27270  (2006)
27271  (2000)
27272  (2001)
27273  (2007)
27274  (2002)
27275  (2014)
27276  (2001)
27277  (2014)

[27278 rows x 1 columns]

XIV. Select rows based on timestamps later than 2015-02-01.

In [35]:
tags[tags['timestamp']>1422729000]

        userId  movieId                       tag   timestamp
301        318      260                     1970s  1424472169
302        318      260                   fantasy  1424472169
303        318      260                    sci-fi  1424472169
304        318   115149                    Action  1424534310
305        318   115149                   Revenge  1424534283
306        318   115149              Willem Dafoe  1424534383
324        342      318                masterplan  1423424898
326        342      318             prison escape  1423424898
327        342      318                redemption  1423424898
492        342    54372                    French  1422734628
493        342    54372            murder mystery  1422734632
494        342    54372              twist ending  1422734630
556        342    89118                disturbing  1422734236
557        342    89118              long revenge  1422734239
558        342    89118                   spanish  1422734293
559        342    89118             unpredictable  1422734224
589        342   108190           based on a book  1426978115
590        342   108190                  dystopia  1426978076
591        342   112556           based on a book  1422733895
592        342   112556                  marriage  1422733850
593        342   112556                meticulous  1422733882
594        342   112556                  mindfuck  1422733866
595        342   112556       Neal Patrick Harris  1422733874
596        342   112556             unpredictable  1422733885
1018       370     6975  breaking the fourth wall  1425242234
1019       370    27592                   violent  1425241975
2203       969       97            class conflict  1426754226
2204       969      288                  mindfuck  1426752631
2205       969      288                  paranoid  1426752639
2206       969      288               psychedelic  1426752634
...        ...      ...                       ...         ...
461895  137227   120222         horribly animated  1422821079
461896  137227   120222              nazi imagery  1422821051
461897  137227   120222                    racist  1422821047
461898  137227   120222        racist stereotypes  1422821071
462190  137249      296               influential  1423437040
462191  137249      296                  neo-noir  1423437040
462192  137249      296         quentin tarantino  1423437040
462195  137277   110052     marcello mastroianni,  1422925214
462979  137924    46855                 Criterion  1427722627
462980  137924    46855         French Resistance  1427722622
462981  137924    46855              World War II  1427722614
463004  138063     4355                    Hockey  1424230535
463005  138063   108160                    Hockey  1424230501
463504  138103    67894                   finnish  1423255773
463509  138103    69442                   finnish  1423255750
463544  138103    73501                   finnish  1423255756
463545  138103    74681                   finnish  1423255760
463573  138103    84553                   finnish  1423255764
464786  138301    52042                 espionage  1426032479
464787  138301    52042       resistance movement  1426032481
464788  138301    52042              World War II  1426032485
464958  138301   109487                 ambitious  1423178287
464959  138301   109487                atmosphere  1423178302
464960  138301   109487                plot holes  1423178186
464961  138301   109487                    sci-fi  1423178227
464962  138301   109487           science fiction  1423178255
464963  138301   109487            Self-Indulgent  1423178219
464964  138301   109487                     space  1423178343
464965  138301   109487        visually appealing  1423178319
464966  138301   109487          wasted potential  1423178212

[12168 rows x 4 columns]

XV. Sort the tags DataFrame based on timestamp.

In [42]:
tags.sort_values(['timestamp'], ascending=True)

        userId  movieId                              tag   timestamp
333932  100371     2788                     monty python  1135429210
333927  100371     1732                    coen brothers  1135429236
333924  100371     1206                  stanley kubrick  1135429248
333923  100371     1193                   jack nicholson  1135429371
333939  100371     5004                    peter sellers  1135429399
333922  100371       47                   morgan freeman  1135429412
333921  100371       47                        brad pitt  1135429412
333936  100371     4011                        brad pitt  1135429431
333937  100371     4011                      guy ritchie  1135429431
333920  100371       32                     bruce willis  1135429442
333933  100371     2858                     kevin spacey  1135429466
333931  100371     2329                     fuckoff nazi  1135429508
333930  100371     2329                    edward norton  1135429508
333944  100371     6016                           brazil  1135429520
15903     3797      110                        overrated  1135589075
256663   75141     4642                         Terrible  1135688095
15926     3797     8573             Nonlinear Surrealism  1135936223
68928    16050    38886                             twee  1136036612
68924    16050    38886                         eighties  1136036612
68925    16050    38886                           family  1136036612
68926    16050    38886                         new york  1136036612
68927    16050    38886                        overrated  1136036612
68919    16050     7060                        christian  1136039301
68921    16050     7060                          musical  1136039301
68920    16050     7060                           kitsch  1136039301
68922    16050     7060                        religious  1136039301
68918    16050     6898                            harsh  1136039368
68916    16050     6898                          british  1136039368
68917    16050     6898                            drugs  1136039368
81444    20513    36529                            truth  1136242623
...        ...      ...                              ...         ...
119997   28906   115149                          violent  1427746031
119991   28906   115149                    lack of story  1427746053
119993   28906   115149                     over the top  1427746060
119989   28906   115149                           cheesy  1427746074
405155  123297   128642                              CLV  1427746337
399877  123297     4211                              CLV  1427746709
400993  123297     6419                              CLV  1427746864
401017  123297     6481                              CLV  1427747220
405123  123297   118722                              CLV  1427747321
400106  123297     4573                              CLV  1427747462
150873   42640   115122                     mockumentary  1427748778
150871   42640   115122                           comedy  1427748797
150872   42640   115122                      dark comedy  1427748808
392905  122523     5004                              USA  1427752289
392904  122523     5004                            party  1427752292
290536   88044   106782              unsatisfying ending  1427753000
290534   88044   106782                           Orgies  1427753111
290529   88044   106782                             ENFP  1427753147
290532   88044   106782             Left-Wing Propaganda  1427753266
290533   88044   106782                Left-Wing Writers  1427753621
290528   88044   106782  Economically Illiterate Writers  1427753739
290530   88044   106782                       inaccurate  1427753806
290531   88044   106782                       Jonah Hill  1427753849
290526   88044   106782                           Amoral  1427753913
290527   88044   106782                            crime  1427753921
290535   88044   106782                        profanity  1427754096
288375   87797      215                           Vienna  1427755801
158763   46072     3409                      premonition  1427760726
158780   46072     6058                      premonition  1427760764
339178  102853   115149                    russian mafia  1427771352

[465564 rows x 4 columns]